# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

draw_tau_cpp <- function(beta, alpha, nu_shape, nu_rate, ns) {
    .Call(`_BridgeChange_draw_tau_cpp`, beta, alpha, nu_shape, nu_rate, ns)
}

draw_sig2_cpp <- function(y, X, beta, state, c0, d0, ns) {
    .Call(`_BridgeChange_draw_sig2_cpp`, y, X, beta, state, c0, d0, ns)
}

draw_beta_svd_cpp <- function(Xm, Ym, lambda, sig2, tau, ns, K) {
    .Call(`_BridgeChange_draw_beta_svd_cpp`, Xm, Ym, lambda, sig2, tau, ns, K)
}

draw_beta_cpp <- function(XX, XY, lambda, sig2, tau, ns, K) {
    .Call(`_BridgeChange_draw_beta_cpp`, XX, XY, lambda, sig2, tau, ns, K)
}

draw_bi_cpp <- function(y, X, W, D, Dinv, XVX_old, XVy_old, SSE_old, sig2, beta, state, time_id, subject_id, N, ns) {
    .Call(`_BridgeChange_draw_bi_cpp`, y, X, W, D, Dinv, XVX_old, XVy_old, SSE_old, sig2, beta, state, time_id, subject_id, N, ns)
}

draw_beta_BCK_cpp <- function(Xm, Ym, lambda, sig2, tau, ns, K) {
    .Call(`_BridgeChange_draw_beta_BCK_cpp`, Xm, Ym, lambda, sig2, tau, ns, K)
}

sparse_panel_state_sampler_cpp <- function(m, T, N, Yt_arr, Xt_arr, Wt_arr, D, beta, sig2, P) {
    .Call(`_BridgeChange_sparse_panel_state_sampler_cpp`, m, T, N, Yt_arr, Xt_arr, Wt_arr, D, beta, sig2, P)
}

sparse_fixed_state_sampler_cpp <- function(m, T, N, Yt_arr, Xt_arr, beta, sig2, P) {
    .Call(`_BridgeChange_sparse_fixed_state_sampler_cpp`, m, T, N, Yt_arr, Xt_arr, beta, sig2, P)
}

sparse_state_sampler_cpp <- function(m, y, X, beta, sig2, P) {
    .Call(`_BridgeChange_sparse_state_sampler_cpp`, m, y, X, beta, sig2, P)
}

#' Negative Binomial State sampler
#' @param m Number of break points.
#' @param y Response vector.
#' @param X Design matrix.
#' @param d Dispersion parameter.
#' @param beta Coefficient matrix.
#' @param P Transition probability matrix.
#' @keywords internal
sparse_state_sampler_NB <- function(m, y, X, d, beta, P) {
    .Call(`_BridgeChange_sparse_state_sampler_NB`, m, y, X, d, beta, P)
}

