# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

draw_tau_cpp <- function(beta, alpha, nu_shape, nu_rate, ns) {
    .Call('_BridgeChange_draw_tau_cpp', PACKAGE = 'BridgeChange', beta, alpha, nu_shape, nu_rate, ns)
}

draw_sig2_cpp <- function(y, X, beta, state, c0, d0, ns) {
    .Call('_BridgeChange_draw_sig2_cpp', PACKAGE = 'BridgeChange', y, X, beta, state, c0, d0, ns)
}

draw_beta_svd_cpp <- function(Xm, Ym, lambda, sig2, tau, ns, K) {
    .Call('_BridgeChange_draw_beta_svd_cpp', PACKAGE = 'BridgeChange', Xm, Ym, lambda, sig2, tau, ns, K)
}

draw_beta_cpp <- function(XX, XY, lambda, sig2, tau, ns, K) {
    .Call('_BridgeChange_draw_beta_cpp', PACKAGE = 'BridgeChange', XX, XY, lambda, sig2, tau, ns, K)
}

draw_bi_cpp <- function(y, X, W, D, Dinv, XVX_old, XVy_old, SSE_old, sig2, beta, state, time_id, subject_id, N, ns) {
    .Call('_BridgeChange_draw_bi_cpp', PACKAGE = 'BridgeChange', y, X, W, D, Dinv, XVX_old, XVy_old, SSE_old, sig2, beta, state, time_id, subject_id, N, ns)
}

draw_beta_BCK_cpp <- function(Xm, Ym, lambda, sig2, tau, ns, K) {
    .Call('_BridgeChange_draw_beta_BCK_cpp', PACKAGE = 'BridgeChange', Xm, Ym, lambda, sig2, tau, ns, K)
}

sparse_panel_state_sampler_cpp <- function(m, T, N, Yt_arr, Xt_arr, Wt_arr, D, beta, sig2, P) {
    .Call('_BridgeChange_sparse_panel_state_sampler_cpp', PACKAGE = 'BridgeChange', m, T, N, Yt_arr, Xt_arr, Wt_arr, D, beta, sig2, P)
}

sparse_fixed_state_sampler_cpp <- function(m, T, N, Yt_arr, Xt_arr, beta, sig2, P) {
    .Call('_BridgeChange_sparse_fixed_state_sampler_cpp', PACKAGE = 'BridgeChange', m, T, N, Yt_arr, Xt_arr, beta, sig2, P)
}

sparse_state_sampler_cpp <- function(m, y, X, beta, sig2, P) {
    .Call('_BridgeChange_sparse_state_sampler_cpp', PACKAGE = 'BridgeChange', m, y, X, beta, sig2, P)
}

#' Negative Binomial State sampler
sparse_state_sampler_NB <- function(m, y, X, d, beta, P) {
    .Call('_BridgeChange_sparse_state_sampler_NB', PACKAGE = 'BridgeChange', m, y, X, d, beta, P)
}

